version: '2.4'

services:

  api:
    depends_on:
      - traefik
    build:
      context: .
      dockerfile: ops/dockerfile/api.Dockerfile
      shm_size: 1gb
    container_name: api
    restart: on-failure
    ports:
      # The HTTP port
      - "7070:7070"
    environment:
      GRPC_CLIENT_PORT: 80
      GRPC_CLIENT_HOST: traefik
      TRACER_SERVICE_NAME: API
      TRACER_URI: jaeger-agent:6831
    cpu_quota: 20000
    mem_limit: 500m
