version: '2.4'

services:

  user:
    depends_on:
      - traefik
    build:
      context: .
      dockerfile: ops/dockerfile/user.Dockerfile
      shm_size: 1gb
    container_name: user
    restart: on-failure
    environment:
      TRACER_SERVICE_NAME: User
      TRACER_URI: jaeger-agent:6831
    cpu_quota: 20000
    mem_limit: 500m
